name: Build and Deploy
on:
  workflow_dispatch:
env:
  duplo_host: https://hrhouz.duplocloud.net
  duplo_token: "${{ secrets.DUPLO_TOKEN }}"
  SERVICE_NAME: parse-server                      
  TENANT_NAME: dev01                        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get AWS credentials
        uses: duplocloud/ghactions-aws-jit@master 
        with:
          tenant: default
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1 
      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    outputs:
      image: "${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://hrhouz.duplocloud.net
      DUPLO_TENANT: dev01
    steps:  
    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-service@v0.0.3
      with:
        service: parse-server
        image: ${{ needs.build.outputs.image }}
  
